# File: .github/workflows/deploy-via-reusable.yml
name: Deploy React App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-react-ci:
    uses: ./.github/workflows/react-ci.yml
    with:
      node-version: "18"
      working-directory: "./"     # if your app lives at repo root
    secrets:
      VERCEL_TOKEN:      ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID:     ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
