# File: .github/workflows/deploy.yml
name: Deploy React App to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # ← This tells Actions to load your "Production" environment secrets:
    environment: Production

    steps:
      # 1) Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Setup Node.js & cache npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # 3) Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4) Build your Vite-powered React app
      - name: Build
        run: npm run build
        env:
          CI: false      # suppresses warnings-as-errors in some setups

      # 5) Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token:       ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id:      ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id:  ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory:  ./            # your project root
          vercel-args:        '--prod'      # production deploy
